version: '3.2'

services:
  db:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - '8082:80'
    environment:
      - PMA_HOST=db
      - PMA_ARBITRARY=1
      # PMA_PORT=3306
      # PMA_USER=root
      # PMA_PASSWORD=secret
